services:
  mongo:
    build: ./mongo
    ports:
      - 27017:27017
    restart: on-failure
    volumes:
      - ~/temp:/data/db 
  server:
    build: ./server
    ports:
      - 8080:80
    restart: on-failure    