services:
  mongo:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    restart: on-failure
    volumes:
      - ~/temp:/data/db
    networks:
      - my_network
  server:
    build: ./server
    ports:
      - 8080:80
    restart: on-failure
    depends_on:
      - mongo
    networks:
      - my_network
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - VALID_TOKEN=test1234
  test:
    build: ./test
    profiles: ["test"]
    depends_on:
      - mongo
      - server
    networks:
      - my_network
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - SERVER_URI=http://192.168.50.100:8080
      - VALID_TOKEN=test1234
networks:
  my_network:
    driver: bridge