services:
  mongo:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    restart: on-failure
    volumes:
      - ~/temp:/data/db
    networks:
      - my_network
  server:
    build: ./server
    ports:
      - 8080:80
    restart: on-failure    
    depends_on:
      - mongo
    networks:
      - my_network
    environment:
      - MONGO_URI=mongodb://mongo:27017
networks:
  my_network:
    driver: bridge